import { Metadata } from '@/node_modules/next/types';

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app About',
};

export default function Home() {
  // useEffect(() => {
  //   console.log('Counter ' + counter);
  //   return function cleanup() {
  //     console.log('Unmount');
  //   };
  // });

  return <div>О нас</div>;
}
