import { Metadata } from '@/node_modules/next/types';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'News',
  description: 'Generated by create next app News',
};

export default function News() {
  // useEffect(() => {
  //   console.log('Counter ' + counter);
  //   return function cleanup() {
  //     console.log('Unmount');
  //   };
  // });

  return <div>News</div>;
}
