import { Metadata } from '@/node_modules/next/types';

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app Login',
};

export default function Login() {
  return <div>Login</div>;
}
