import { Metadata } from '@/node_modules/next/types';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'News',
  description: 'Generated by create next app News',
};

export default function Login() {

  return <div>Login</div>;
}
